###

### Get all users in csv format
GET http://localhost:8080/api/users/all
###

### Get all posts in csv format
GET http://localhost:8080/api/posts/all
###

### Get all groups in csv format
GET http://localhost:8080/api/groups/all
###

### Get all saved posts in csv format
GET http://localhost:8080/api/savedPosts/all
###

### Get all joined groups in csv format
GET http://localhost:8080/api/groups/joinedGroups/all
###

