name: Backend CI/CD

on:
  push:
    branches:
      - main
      - dev
      - devV2

  pull_request:
    branches:
      - main
      - dev
      - devV2
      

jobs:

  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out Code
        uses: actions/checkout@v2


  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Print environment variables
        run: printenv | grep 'DB_URL\|DB_USER\|DB_PASS\|JWT_SECRET_KEY'

      - name: Set environment variables
        run: |
          echo "JWT_SECRET_KEY=${{ secrets.JWT_SECRET_KEY }}" >> $GITHUB_ENV
          echo "DB_URL=${{ secrets.DB_URL }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}" >> $GITHUB_ENV
          echo "GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}" >> $GITHUB_ENV

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: backend/Lookout

      - name: Build and Test with Gradle
        run: ./gradlew test
        working-directory: backend/Lookout
